// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC33EZsVWfZpxSFfdGv7jQuUwilKorUxLQ',
    appId: '1:1069717813729:web:1c145e5307a6ea0a0ffaa0',
    messagingSenderId: '1069717813729',
    projectId: 'driveauto-ed6b7',
    authDomain: 'driveauto-ed6b7.firebaseapp.com',
    storageBucket: 'driveauto-ed6b7.firebasestorage.app',
    measurementId: 'G-YZTC88MPD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDxkwyA-e1CALGbVjvfDVLUOFNbqkFwKk',
    appId: '1:1069717813729:android:2b30d2efb9ec8bcc0ffaa0',
    messagingSenderId: '1069717813729',
    projectId: 'driveauto-ed6b7',
    storageBucket: 'driveauto-ed6b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhAhvhjXEI8d0XfOSUbvt1Kd40O1hDR5o',
    appId: '1:1069717813729:ios:115ead18b364ec4d0ffaa0',
    messagingSenderId: '1069717813729',
    projectId: 'driveauto-ed6b7',
    storageBucket: 'driveauto-ed6b7.firebasestorage.app',
    iosClientId: '1069717813729-u6dgj3l7ahj8p26vg4ttt4nmcs81gbfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDriveautoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhAhvhjXEI8d0XfOSUbvt1Kd40O1hDR5o',
    appId: '1:1069717813729:ios:115ead18b364ec4d0ffaa0',
    messagingSenderId: '1069717813729',
    projectId: 'driveauto-ed6b7',
    storageBucket: 'driveauto-ed6b7.firebasestorage.app',
    iosClientId: '1069717813729-u6dgj3l7ahj8p26vg4ttt4nmcs81gbfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDriveautoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC33EZsVWfZpxSFfdGv7jQuUwilKorUxLQ',
    appId: '1:1069717813729:web:63a53b4d023bf5a40ffaa0',
    messagingSenderId: '1069717813729',
    projectId: 'driveauto-ed6b7',
    authDomain: 'driveauto-ed6b7.firebaseapp.com',
    storageBucket: 'driveauto-ed6b7.firebasestorage.app',
    measurementId: 'G-XGW5Q2RDJR',
  );
}
